name: clean_arch_experts
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1


scripts: 
  test: flutter test --coverage test/
  gen_coverage: genhtml coverage/lcov.info -o coverage/html
  analyze: dartanalyzer .
  format: dartfmt -w .



environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dartz: ^0.10.0-nullsafety.2
  mocktail: ^0.1.2
  equatable: ^2.0.2
  dio: ^4.0.0
  get_it: ^7.1.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
      - assets/mock/user.json